#!/bin/bash

# scaffolding for tests
# MUST create test db (erp_test) via ERP_PB_DBNAME FIRST!
# meant to be run from top source-dir ONLY

export ERP_PB_DBNAME="erp_test"

psql --dbname=$ERP_PB_DBNAME \
     --quiet \
     --file=migrations/up/1_setup.sql 
psql --dbname=$ERP_PB_DBNAME \
     --quiet \
     --file=migrations/up/2_users_tokens.sql
psql --dbname=$ERP_PB_DBNAME \
     --quiet \
     --file=migrations/up/3_markup_rates.sql
psql --dbname=$ERP_PB_DBNAME \
     --quiet \
     --file=migrations/up/4_project_sections.sql
psql --dbname=$ERP_PB_DBNAME \
     --quiet \
     --file=migrations/up/5_categories.sql
psql --dbname=$ERP_PB_DBNAME \
     --quiet \
     --file=migrations/up/6_line_item_length.sql
psql --dbname=$ERP_PB_DBNAME \
     --quiet \
     --file=migrations/up/7_pricing_lists.sql
psql --dbname=$ERP_PB_DBNAME \
     --quiet \
     --file=migrations/up/8_cam_data_changes.sql
psql --dbname=$ERP_PB_DBNAME \
     --quiet \
     --file=migrations/up/9_warm_air_stock.sql
psql --dbname=$ERP_PB_DBNAME \
     --quiet \
     --file=migrations/up/10_feedback_complaints.sql
psql --dbname=$ERP_PB_DBNAME \
     --quiet \
     --file=migrations/up/11_more_markup_types.sql
psql --dbname=$ERP_PB_DBNAME \
     --quiet \
     --file=migrations/up/12_more_cats.sql
psql --dbname=$ERP_PB_DBNAME \
     --quiet \
     --file=migrations/up/13_assembly_overhaul.sql
psql --dbname=$ERP_PB_DBNAME \
     --quiet \
     --file=migrations/up/14_customer_discounts.sql
psql --dbname=$ERP_PB_DBNAME \
     --quiet \
     --file=migrations/up/15_progressive_billing_support.sql
psql --dbname=$ERP_PB_DBNAME \
     --quiet \
     --file=migrations/up/16_mult_cust_list.sql
psql --dbname=$ERP_PB_DBNAME \
     --quiet \
     --file=migrations/up/17_user_permissions.sql
psql --dbname=$ERP_PB_DBNAME \
     --quiet \
     --file=migrations/up/18_order_complete_flag.sql
psql --dbname=$ERP_PB_DBNAME \
     --quiet \
     --file=migrations/up/19_purchase_orders_tweaks.sql

# now need to run the QB -> database transfers -> as tests if possible!
